---
version: "2.1"
services:
  wiki:
    image: nicholaswilde/wiki:latest
    container_name: wiki-default
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - data:/data
volumes:
  data:
